### ISSUE TITLE
SemVer to int32: Version string invalid, 18229 is too large

### ISSUE THREAD

**Issue by mauricioQrails** [4tecture/BuildVersioning#11]
hi, 

I am getting the following error 
2018-08-17T18:02:18.9325392Z ##[error]SemVer to int32: Version string invalid, 18229 is too large

can you help?

thanks, Mauricio

**Comment by marc-mueller** [comment]
Hi Mauricio

In this case you need to choose another calculation algorithm for Version code calculation.

Details:
We extended the versioning task to calculate a version number. This is needed for Android Manifests. We convert the Digits into a single incrementing number. The standard definition is to use a SemVer conversion. To go from a SemVer to an integer, we only have 10 bits per digit, which results in a max value of 1024 per digit (x.x.x). We didn’t implement a way to disable that functionality since we are generating variables with this value. 
Please choose the first option which should resolve the problem. 

Best
Marc
